server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    autoindex on;

    # OSTree clients expect these content types
    location ~* \.zstd$ {
        add_header Content-Type application/zstd;
    }
    location ~* \.gz$ {
        add_header Content-Type application/gzip;
    }
    location / {
        try_files $uri $uri/ =404;
    }
}
